local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   update_frequency: 100.0
   publish_frequency: 100.0
   width: 10.0
   height: 10.0
   resolution: 0.05
   static_map: false
   rolling_window: true
